name: Keep Vercel Bot Awake
on:
  schedule:
    - cron: '*/4 * * * *' # Ogni 4 minuti
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s https://markethubshop-bot.vercel.app/api/index
